### ISSUE TITLE
Issues with this template.   Service LB doesn't allow access to problemic pod.   pgsql Pod does not reload data when killed.

### ISSUE THREAD

**Issue by alberttwong** [redhat-developer/s2i-aspnet-musicstore-ex#13]
You can't just kill the pqsql pod and it'll just restart with the dataload and then make itself ready for work.   Then the other problem is the pgsql service and not allowing connectivity to the problemtic pod.

**Comment by alberttwong** [comment]
The way I got pass the problemic pod was to delete the readiness probe because it checks if the musicbox database exists.   

Chicken and egg problem.... pqsql doesn't pass readiness, which means removed from service and then the app can't connect to populate the database.

**Comment by tmds** [comment]
Fixed by https://github.com/redhat-developer/s2i-dotnetcore/pull/257
