### ISSUE TITLE
Please document the s2i-supported branches

### ISSUE THREAD

**Issue by omajid** [redhat-developer/s2i-aspnet-musicstore-ex#2]
I see a number of branches; many of them don't have s2i support. Could we please document which branches have s2i support and which versions of .NET Core they are compatible with?

**Comment by tmds** [comment]
@omajid only the rel/1.1.0-preview1 is supported. This is also the default branch of the repo.
Perhaps we should just get rid of all branches we don't use (including master)?

**Comment by jerboaa** [comment]
We should keep it compatible with upstream MusicStore. i.e. keep branches and document additional branches which are meant for s2i. This would make merging in upstream changes easier.

**Comment by omajid** [comment]
I agree with @jerboaa . Additionally the name `rel/1.1.0-preview1` confuses me. Does that correspond to the 1.1.0 release? Various .NET Core versions claim to be `1.0.0-preview*`. I have not come across `1.1.0-preview*` before.

**Comment by tmds** [comment]
> We should keep it compatible with upstream MusicStore. i.e. keep branches and document additional branches which are meant for s2i. This would make merging in upstream changes easier.

How is merging easier by having unused upstream branches in our repo?

> I agree with @jerboaa . Additionally the name rel/1.1.0-preview1 confuses me. Does that correspond to the 1.1.0 release? Various .NET Core versions claim to be 1.0.0-preview*. I have not come across 1.1.0-preview* before.

It confuses me too. It is the name of the upstream 1.1 branch.

**Comment by tmds** [comment]
@jerboaa @omajid this is how I'd do an update: add upstream remote, fetch remote, merge remote branch. Keeping the same branch name as the upstream makes it straight-forward what branch to merge in. The unsupported branches don't have use, so I'd remove them. Does this sound like a good approach? Or how do you want to do this?

**Comment by jerboaa** [comment]
I'm fine with removing branches we don't use. The ones we do use should be mergeable upstream. Maybe consider calling the branches with some extra bits something else. It would give users an easy way to see that we use branch X 1-to-1. Branch Y would be X+our bits. Just an idea.

I'd like to avoid divergence (introduce incompatible changes) from upstream is all.

Either way, we should document how it works.
